apiVersion: v2
name: wordpress
description: A Helm chart for Kubernetes

type: application

version: 0.2.1

# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v1.0.0"
